django-boiler-plate/board/urls.py
from django.urls import path

from . import views

app_name = 'board'

urlpatterns = [
    path('', views.list, name='list'),
    path('post/', views.post, name='post'),
    path('read/<int:post_id>/', views.read, name='read'),
    path('update/<int:post_id>/', views.update, name='update'),
    path('delete/<int:post_id>/', views.delete, name='delete'),
    path('ajaxList', views.ajaxList, name='ajaxList'),
]

django-boiler-plate/common/urls.py
from django.urls import path
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('mypage/', views.mypage, name='mypage'),
    path('editProfile/', views.editProfile, name='editProfile'),
    path('deleteMember/', views.deleteMember, name='deleteMember'),
    path('findIdPwd/', views.findIdPwd, name='findIdPwd')
]

django-boiler-plate/config/urls.py
# from django.contrib import admin
from django.urls import path, include
from common.views import home

urlpatterns = [
    path('', home, name='home'),
    path('user/', include('common.urls')),
    path('board/', include('board.urls'))
]

django-boiler-plate/board/models.py
from django.db import models

# Create your models here.
class Board(models.Model):
    post_id = models.AutoField(primary_key=True, verbose_name='게시글 아이디')
    category = models.CharField(max_length=128, default="기본 게시판", verbose_name='카테고리')
    title = models.CharField(max_length=256, null=True, verbose_name='게시글 제목')
    contents = models.TextField(verbose_name='게시글 내용')
    writer = models.CharField(max_length=32, verbose_name='작성자')
    register_date = models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록일')

    class Meta:
        db_table = 'board'
        verbose_name = '게시판'
        verbose_name_plural = '게시판'

django-boiler-plate/common/models.py
from django.db import models

class User(models.Model):
    idx = models.AutoField(verbose_name='index', primary_key=True)
    user_id = models.CharField(max_length=32, unique=True, verbose_name='유저 아이디')
    user_pwd = models.CharField(max_length=128, verbose_name='유저 비밀번호')
    user_name = models.CharField(max_length=16, unique=True, verbose_name='유저 이름')
    user_email = models.EmailField(max_length=128, verbose_name='유저 이메일')
    user_register_date = models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록일')
    user_auth = models.SmallIntegerField(default=0, null=True, verbose_name='유저 권한')
    
    class Meta:
        db_table = 'user'
        verbose_name = '유저'
        verbose_name_plural = '유저'

django-boiler-plate/board/views.py
from django.http.response import JsonResponse
from django.shortcuts import redirect, render
from django.http import HttpResponse
from board.service import BoardControl
# Create your views here.

def authCheck(function):
    def wrapper(request, post_id = ''):
        if 'user_id' in request.session: # 로그인 상태
            if post_id == '': # post_id 값이 없을 때는 로그인만 체크
                return function(request)  
            else: # (업데이트, 삭제) 접속한 사람과 작성자 매치
                board = BoardControl()
                result = board.writerCheck(post_id, request.session['user_id'])
                if result: # 글 작성자와 접속한 사람이 같다.
                    return function(request, post_id)
                else: return redirect('/') # 글 작성자와 접속한 사람이 다르다.
        else: # 로그인 상태가 아니다.
            return redirect('/')
    return wrapper

def list(request):
    context = { 'page': 'list' }
    board = BoardControl()
    context['list'] = board.list({ 'start': 0, 'length': 10 })
    return render(request, 'main.html', context)

@authCheck
def post(request):
    context = { 'page': 'post' }

    if request.method == 'POST':
        board = BoardControl()
        board.insert(request)
        return redirect('/')
    return render(request, 'main.html', context)    

def read(request, post_id):
    context = { 'page': 'read' }
    board = BoardControl()
    context['contents'] =  board.read(post_id)
    return render(request, 'main.html', context)

@authCheck
def update(request, post_id):
    context = { 'page': 'update' }
    board = BoardControl()
    context['contents'] =  board.read(post_id)
    if request.method == 'POST':
        board.update(request, post_id)
        print(request.POST)
        return redirect('/board/read/' + str(post_id) + '/')
    return render(request, 'main.html', context)

@authCheck
def delete(request, post_id):
    board = BoardControl()
    board.delete(post_id)
    return redirect('/')

def ajaxList(request):
    board = BoardControl()
    
    start = request.GET.get('now', 0)
    length = request.GET.get('length', 10)

    start = (int(start) - 1) * 10 
    
    context = board.list({ 'start': start, 'length': length }) 
    count = board.list({ 'count': True }) 

    # length = limit
    # start = offset 
    return JsonResponse({ 'list': context, 'count': count[0]['count'] })

django-boiler-plate/common/views.py
from django.http.response import JsonResponse
from django.shortcuts import redirect, render
from django.http import HttpResponse
from common.service import Authentication
from board.service import BoardControl

# Create your views here.

def loggedIn(function):
    def wrapper(request):
        if 'user_id' in request.session:
            return function(request)
        redirect('/')
    return wrapper

def notLoggedIn(function):
    def wrapper(request):
        if 'user_id' in request.session:
            return redirect('/')
        return function(request)
    return wrapper

def home(request):
    context = {}
    board = BoardControl()
    context['list'] = board.list({ 'start': 0, 'length': 10 })
    return render(request, 'main.html', context)

@notLoggedIn
def login(request):
    context = {}
    if request.method == 'POST' :
        auth = Authentication(request)
        result = auth.login()
        context = { 'message': result['message'] }

        if result['pass']:
            request.session['user_id'] = result['user_id']
            request.session['user_name'] = result['user_name']
            return redirect('/')
    return render(request, 'common/login.html', context)

@notLoggedIn
def register(request):
    context = {}
    if request.method == 'POST' :
        auth = Authentication(request)
        result = auth.register()

        context = { 'message': result['message'] }
        if result['pass']:
            return redirect('/user/login/')
    return render(request, 'common/register.html', context)

@loggedIn
def logout(request):
    request.session.flush()
    return redirect('/')

@loggedIn
def mypage(request):
    context = {}
    auth = Authentication(request)
    context['result'] = auth.getMemberInfo(request.session['user_id'])
    return render(request, 'common/mypage.html', context)

@loggedIn
def editProfile(request):
    context = {}
    auth = Authentication(request)
    context['result'] = auth.getMemberInfo(request.session['user_id'])

    if request.method == 'POST':
        auth = Authentication(request)
        auth.updateProfile(request.session['user_id'])
        return redirect('/user/mypage/')

    return render(request, 'common/editProfile.html', context)

@loggedIn
def deleteMember(request):
    auth = Authentication(request)
    auth.deleteMember(request.session['user_id'])
    request.session.flush()
    return redirect('/')

@notLoggedIn
def findIdPwd(request):
    context = {}
    
    if request.method == 'POST':
        auth = Authentication(request)
        result = auth.temporaryPassword()
        return JsonResponse({ 'result': result })

    return render(request, 'common/findIdPwd.html', context)

django-boiler-plate/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token }}">
    <title>상민 과제</title>
    <link rel="stylesheet" href="{% static 'css/quill.snow.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/lib/prefixfree.min.js' %}"></script>
    <script src="{% static 'js/lib/jquery-3.6.0.min.js' %}"></script>
</head>
<body>
    {% include "header.html" %}
    <div class="center">
        {% block content %}
        {% endblock %}
    </div>
    {% include "footer.html" %}
    <script>        
        $.ajaxSetup({headers: {"X-CSRFToken": "{{csrf_token}}"}})
    </script>
    <script src="{% static 'js/util.js' %}"></script>
    <script src="{% static 'js/common.js' %}"></script>
</body>
</html>

django-boiler-plate/templates/board/list.html
{% load tz %}
<section class="writing-list board-css-sync">
    <h2>글 목록</h2>
    <ul class="view" id="view">
        <li>
            <div>글번호</div>
            <div>글제목</div>    
            <div>작성자</div>
            <div>등록일</div>
        </li>
        {% for item in list %}
        <li>
            <div>{{ item.post_id }}</div>
            <div><a href="{% url 'board:read' post_id=item.post_id %}">{{ item.title }}</a></div>
            <div>{{ item.writer }}</div>
            <div>{{ item.register_date | date:'Y.m.d' }}</div>
        </li>
        {% empty %}
        <li class="grid-add">작성된 글이 없습니다.</li>
        {% endfor %}
    </ul>
</section>
{% include "board/pagination.html" %}

django-boiler-plate/templates/board/pagination.html
<div class="pagination" id="pagination">
    <ol class='list'>
        
    </ol>
</div>

django-boiler-plate/templates/board/post.html
{% load static %}
<secion class="post-page board-css-sync">
    {% if page == 'post' %}
    <h2>글 작성 페이지</h2>
    <div class="post-container">
    <form id="quillForm" action="{% url 'board:post' %}" method="post">
        {% csrf_token %}
        <input type="text" name="title" id="title" placeholder="제목을 입력하세요." />
        <div id="editor"> 
            
        </div>
        </div>
        <div class="post-button">
            <button type="submit" class="button">작성</button>
            <button type="button" class="button" id="postCancel">취소</button>
        </div>
        <input type="hidden" name="about">
    </form>
    {% elif page == 'update' %}
    <h2>글 수정 페이지</h2>
    <div class="post-container">
    <form id="quillForm" action="{% url 'board:update' post_id=contents.post_id %}" method="post">
        {% csrf_token %}
        <input type="text" name="title" id="title" value="{{ contents.title }}" placeholder="제목을 입력하세요." />
        <div id="editor"> 
            
        </div>
        </div>
        <div class="post-button">
            <button type="submit" class="button">수정</button>
            <button type="button" class="button" id="updateCancel" value="{{ contents.post_id }}">취소</button>
        </div>
        <input type="hidden" name="about">
        <input type="hidden" id="update" value="{{ contents.contents }}">
    </form>
    {% endif %}
</secion>
<script src="{% static 'js/lib/quill.js' %}"></script>
<script src="{% static 'js/quillControl.js' %}"></script>
<!-- ?now={% now 'jS F Y H:i' %} -->

django-boiler-plate/templates/board/read.html
{% load static %}
{% if error %}
<script>
    alert("{{error}}")
</script>
{% endif %}
<section class="read-post board-css-sync">
    <h2>글을 가져왔어요 ~</h2>
    <div class="view">
        <div class="title">
            <h3>{{ contents.title }}</h3>
            <div>
                {{ contents.writer }} / {{ contents.register_date }}
            </div>
        </div>
        <div class="contents" id="contents">
            
        </div>
    </div>
    <div class="hidden quill-wrapper">
        <div id="editor">

        </div>
    </div>
    {% if request.session.user_id == contents.writer %}
    <div class="post-button">
        <a href="{% url 'board:update' post_id=contents.post_id %}" class="button">수정</a>
        <a href="{% url 'board:delete' post_id=contents.post_id %}" class="button" id="confirmDelete">삭제</a>
    </div>
    {% endif %}
    <input type="hidden" id="contentsValue" value="{{ contents.contents }}">
</section>
<script src="{% static 'js/lib/quill.js' %}"></script>
<script src="{% static 'js/quillControl.js' %}"></script>

django-boiler-plate/templates/common/editProfile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="profile-wrap">
    <h2>회원 정보 수정</h2>
    <form action="{% url 'common:editProfile' %}" method="post">
        {% csrf_token %}
        <div class="container">
            <div class="inner">
                <div class="item">
                    <label for="user_id">아이디</label>
                    <input type="text" name="user_id" id="user_id" disabled value="{{ result.user_id }}">
                </div>
                <div class="item">
                    <label for="user_name">이름</label>
                    <input type="text" name="user_name" id="user_name" value="{{ result.user_name }}">
                </div>
                <div class="item">
                    <label for="user_pwd">비밀번호</label>
                    <input type="password" id="user_pwd" name="user_pwd">
                </div>
                <div class="item">
                    <label for="user_email">이메일</label>
                    <input type="email" id="user_email" name="user_email" value="{{ result.user_email }}">
                </div>
                <div id="user_register_date" class="item">
                    <div class="label">가입일</div>
                    <div>{{ result.user_register_date }}</div>
                </div>
            </div>
        </div>
        <div class="profile-button">
            <button type="submit" class="button">수정하기</button>
            <a href="{% url 'common:mypage' %}" class="button">취소</a>
        </div>
    </form>
</section>
{% endblock %}

django-boiler-plate/templates/common/findIdPwd.html
{% extends 'base.html' %}
{% block content %}
<section class="find-pwd-wrap">    
    <h2>비밀번호 찾기</h2>
    <form action="{% url 'common:findIdPwd' %}" method="post" name="findIdPwd">
        {% csrf_token %}
        <div>
            <label for="user_name">이름</label>
            <input type="text" name="user_name" id="user_name">
        </div>
        <div>
            <label for="user_email">이메일</label>
            <input type="email" name="user_email" id="user_email">
        </div>
        <button type="button" class="button" id="findIdPwd">임시 비밀번호 발급</button>
    </form>
</section>
{% endblock %}

django-boiler-plate/templates/common/login.html
{% extends 'base.html' %}
{% block content %}
<section class="login-wrap">    
    <h2>로그인</h2>
    <form action="{% url 'common:login' %}" method="post">
        {% csrf_token %}
        <div>
            <label for="user_id"></label>
            <input type="text" name="user_id" id="user_id" placeholder="아이디를 입력해주세요.">
        </div>
        <div>
            <label for="user_pwd"></label>
            <input type="password" name="user_pwd" id="user_pwd" placeholder="비밀번호를 입력해주세요.">
        </div>
        <div>
            <button type="submit" class="button">로그인</button>
            <a href="{% url 'common:findIdPwd' %}" class="button">비밀번호 찾기</a>
        </div>
        <div class="error">
        {% if message %}
            {{ message }}
        {% endif %}
        </div>
    </form>
</section>
{% endblock %}

django-boiler-plate/templates/common/mypage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="profile-wrap">
    <h2>마이 페이지</h2>
    <div class="container">
        <h3>프로필</h3>
        <div class="inner">
            <div id="user_id" class="item">
                <div class="label">아이디</div>
                <div>{{ result.user_id }}</div>
            </div>
            <div id="user_name" class="item">
                <div class="label">이름</div>
                <div>{{ result.user_name }}</div>
            </div>
            <div id="user_email" class="item">
                <div class="label">이메일</div>
                <div>{{ result.user_email }}</div>
            </div>
            <div id="user_register_date" class="item">
                <div class="label">가입일</div>
                <div>{{ result.user_register_date }}</div>
            </div>
        </div>
    </div>
    <form action="{% url 'common:deleteMember' %}" method="post" id="deleteMemberForm">
        {% csrf_token %}
        <div class="profile-button">
            <a href="{% url 'common:editProfile' %}" class="button">정보 수정</a>
            <button type="submit" id="deleteMember" class="button">회원 탈퇴</button>
        </div>
    </form>
</section>
{% endblock %}

django-boiler-plate/templates/common/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="register-wrap">
    <h2>회원가입</h2>
    <form action="{% url 'common:register' %}" method="post">
        {% csrf_token %}
        <div>
            <label for="user_id">아이디</label>
            <input type="text" name="user_id" id="user_id">
        </div>
        <div>
            <label for="user_pwd">비밀번호</label>
            <input type="password" name="user_pwd" id="user_pwd">
        </div>
        <div>
            <label for="user_pwd_confirm">비밀번호 확인</label>
            <input type="password" name="user_pwd_confirm" id="user_pwd_confirm">
        </div>
        <div>
            <label for="user_name">이름</label>
            <input type="text" name="user_name" id="user_name">
        </div>
        <div>
            <label for="user_email">이메일</label>
            <input type="email" name="user_email" id="user_email">
        </div>
        <div class="between">
            <div class="error">
                {% if message %}
                {{ message }}
                {% endif %}
            </div>
            <div class="flex">
                <button type="submit" class="button">가입하기</button>
                <a href="/" class="button">취소</a>
            </div>
        </div>
    </form>
</section>
{% endblock %}

django-boiler-plate/templates/header.html
<header class="base-header">
    <div class="inner">
        <div class="logo">
            <h1><a href="{% url 'home' %}">LOGO</a></h1>
        </div>
        <nav>
            {% if request.session.user_id %}
            <ul class="dropdown">
                <li>{{ request.session.user_id }}
                    <ul>
                        <li><a href="{% url 'common:mypage' %}">나의 정보</a></li>
                        <li><a href="#">기타</a></li>
                        <li><a href="#">테스트</a></li>
                    </ul>
                </li>
            </ul>
            <a href="{% url 'common:logout' %}">로그아웃</a>
            {% else %}
            <a href="{% url 'common:login' %}">로그인</a>
            <a href="{% url 'common:register' %}">회원가입</a>
            {% endif %}
        </nav>
    </div>
</header>
<div class="header-space"></div>

django-boiler-plate/templates/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="main-page">
    <div class="main-sidebar">
        {% include "sidebar.html" %}
    </div>
    <div class="main-contents">
        <div>
        </div>
        <div>
            {% if page == 'post' or page == 'update' %}
                {% include "board/post.html" %}
            {% elif page == 'read' %}
                {% include "board/read.html" %}
            {% else %}
                {% include "board/list.html" %}
            {% endif %}
        </div>
    </div>
</main>
{% endblock %}

django-boiler-plate/templates/sidebar.html
{% load static %}
<aside class="post-category-list">
    <nav>
        <div class="writing">
            <a href="{% url 'board:post' %}">글쓰기</a>
        </div>
        <div>
            <a href="{% url 'board:list' %}">기본 게시판</a>
        </div>
    </nav>
</aside>